encoding: utf-8
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-cayman
#remote_theme:  kitian616/jekyll-TeXt-theme   # hosted on github

title: AMAP Bio Antibes
description: Association l'AMAP Bio Antiboise
email: bureau_amapbioantibes @ framalistes.org

show_downloads: false
lang: fr
is_project_page: false
